language: go

go:
  - 1.9.2

env:
  global:
   - ARCH=$(go env GOARCH)
   - TAG=$(git describe --tags --always)
   - IMAGEID=$(docker images -q openebs/node-disk-manager-$ARCH:$TAG)

sudo: required

services:
  - docker

install:
  - make bootstrap

script:
  - make && make test

before_script:
  - mkdir -p $HOME/gopath/src/github.com/openebs
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/github.com/openebs/node-disk-manager
  - cd $HOME/gopath/src/github.com/openebs/node-disk-manager

after_success:
  - if [ "$TRAVIS_BRANCH" = "travis_ci" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      export REPO=openebs/node-disk-manager-$ARCH;
      docker login -u "$DNAME" -p "$DPASS";
      docker push $REPO:$TAG;
      docker tag $IMAGEID $REPO:latest
      docker push $REPO:latest;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      export REPO=openebs/node-disk-manager-$ARCH;
      docker login -u "$DNAME" -p "$DPASS";
      docker push $REPO:$TRAVIS_TAG;
      docker tag $IMAGEID $REPO:latest
      docker push $REPO:latest;
    fi
