language: go

go:
  - 1.9

env:
  global:
   - ARCH=${go env GOARCH}

sudo: required

services:
  - docker

install:
  - make bootstrap

script:
  - make && make test

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then 
     export REPO=openebs/node-disk-manager-$ARCH;
     docker login -u "$DNAME" -p "$DPASS" && docker push $REPO; 
    fi
